@startuml ApresentacaoJogo
hide empty members
skinparam classAttributeIconSize 0

class Game {
  +id: UInt
  --
  +placeTile(player: Player, position: BoardPosition, tile: Tile, idx: UInt): Game
  +nextTurn(): Game
  +startTurnDraw(): Game
}

class Player {
  +hand: Map<UInt, Tile>
  --
  +addToHand(card: Tile): Player
  +removeFromHand(idx: UInt): Player
}

class Spectator { }

class Board {
  --
  +checkBlocked(position: BoardPosition, tile: Tile)
  +place(position: BoardPosition, tile: Tile): Board
}

class BoardTile { }

class BoardPosition {
  +x: Int
  +y: Int
  --
  +neighbour(direction: Direction): BoardPosition
  +coords(): String
}

class Tile {
  --
  +canConnectTo(dir: Direction, tile: Tile): Boolean
  +rotate(right: Boolean): Tile
  +getBlocked(adjTiles: List<Pair<Direction, BoardTile>>): List<Direction>
  +getAdjacent(tiles: BoardTiles, targetPos: BoardPosition): List<Pair<Direction, BoardTile>>
  +codeString(): String
}

enum Direction {
  EAST
  NORTH
  SOUTH
  WEST
}

class Turn {
  +gameTurn: UInt
  +playerTurn: List<UInt>
  --
  +turnString(): String
}

class User {
  +id: UInt
}

class BoardTiles <<typealias>> {
  List<BoardTile>
}

class TileDeck <<typealias>> {
  Map<Tile, UInt>
}

Game *-- "2..*" Player : players
Game *-- "0..*" Spectator : spectators
Game *-- Board : board
Game *-- TileDeck : tileDeck
Game *-- Turn : turn

Player o-- User : user
Player *-- "0..*" Tile : hand

Spectator o-- User : user

Board *-- BoardTiles : tiles
BoardTiles *-- "0..*" BoardTile

BoardTile *-- BoardPosition : pos
BoardTile *-- Tile : tile

Tile *-- "1..*" Direction : connections

TileDeck *-- "0..*" Tile : copies

@enduml
