@startuml DominioBoard
hide empty members
skinparam classAttributeIconSize 0

class Board {
  +tiles: BoardTiles
  --
  +checkBlocked(position: BoardPosition, tile: Tile)
  +placeTile(position: BoardPosition, tile: Tile): Board
  +placeCharacter(position: BoardPosition, character: Character): Board
  +equipItem(position: BoardPosition, player: Player, item: Item): Board
  +unequip(character: PlayableCharacter, item: Item): Board
  +reduceCooldown(): Board
  +replaceBoardTile(updatedTile: BoardTile): Board
}

class BoardTile {
  +pos: BoardPosition
  +tile: Tile
  +cooldown: UInt?
  +character: Character?
  --
  +directionTo(other: BoardTile): Direction?
}

class BoardPosition {
  +x: Int
  +y: Int
  --
  +neighbour(direction: Direction): BoardPosition
  +toString(): String
}

class Tile {
  +connections: List<Direction>
  +specialEffect: TileEffect
  --
  +canConnectTo(dir: Direction, tile: Tile): Boolean
  +rotate(right: Boolean): Tile
  +getBlocked(adjTiles: List<Pair<Direction, BoardTile>>): List<Direction>
  +getAdjacent(tiles: BoardTiles, targetPos: BoardPosition): List<Pair<Direction, BoardTile>>
  +toString(): String
}

enum Direction {
  EAST
  NORTH
  SOUTH
  WEST
}

class TileEffect {
  +type: TileEffectTypes
  +maxCooldown: UInt
  +info: String
}

enum TileEffectTypes {
  None
  Start
  Chest
  BigChest
  StatUp
  StatDown
  StatUpAoE
  StatDownAoE
}

class BoardTiles <<typealias>> {
  List<BoardTile>
}

Board *-- BoardTiles : tiles
BoardTiles *-- "0..*" BoardTile

BoardTile *-- BoardPosition : pos
BoardTile *-- Tile : tile
BoardTile o-- "0..1" Character : character

Tile *-- "1..*" Direction : connections
Tile *-- TileEffect : specialEffect

TileEffect *-- TileEffectTypes : type

@enduml
